spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: mtzz_db
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-url:  ${spring.application.name}:${spring.application.instance_id:${random.value}}
